language: python
python:
  - "2.6"
  - "2.7"
install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements-dev.txt"
  - "pip install coveralls"
script:
  - "coverage run --source=coffee `which nosetests` coffee"
after_success:
  - coveralls