language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements-dev.txt"
  - "pip install coveralls"
script:
  - "flake8 coffee setup.py"
  - "coverage run --source=coffee `which nosetests` coffee"
after_success:
  - coveralls
